@startuml Activity Diagram

start
    :Display search interface;
    repeat :User enters search;
    if(Is search valid?) then (Valid)
        if(results found?) then (Results found)
            :Display information;
        else (No results found)
            :No results found message;
        endif
    else (Not valid)
        :Show error;
    endif
    repeat while (Perform another search?) is (Yes)
    ->No;
end

@enduml