@startuml Deployment Diagram

node "<<Device>> HPE Proliant ML350" as server {
    node Docker {
        node "<<Web Server>> Apache" as Apache {
            file index.php
            file db.php
        }
        node "<<Application>> Updater" as Updater
        node "<<Application>> PostGreSQL" as Postgres {
            database "DB"
        }
        Updater -(0- Postgres
        Postgres -0)- Apache
    }
    file Dockerfile
    Dockerfile - Docker
}

node "<<Device>> Mobile Phone" as Phone {
    node "<<Mobile App>> Huntref" as Huntref {
        file "Local Cache"
        node "<<UI>> Map"
    }
    Apache -0)- Huntref
}

cloud "<<Remote Server>> Data server" as Data {

}
Updater -(0- Data

@enduml
