@startuml
skinparam lifelineStrategy solid
actor User

User -> Map ++ : Open app
loop for all Animals
    Map -> Animal ** : <<Create>>
end

loop for all Areas
    Map -> Area ** : <<Create>>
end

loop for all animals in each area
    Map -> AnimalSeason ** : <<Create>>
end

return Ready, Show map

User -> Map ++ : Select Area

    loop for all aninals in this area
        Map -> Area ++ : getAnimalSeasons()
        return
        Map -> AnimalSeason ++ : getAnimalName()
            AnimalSeason -> Animal ++ : getName()
            return
        return
    end

return Show Animals

User -> Map ++ : Select Animal

    Map -> AnimalSeason ++ : getAnimalName()
        AnimalSeason -> Animal ++ : getName()
        return
    return
    Map -> AnimalSeason ++ : getSeasonDates()
    return

return Show detailed information


@enduml
